const glossary = {
  'blockchain': 'A distributed digital ledger that records transactions across many computers so the record cannot be altered retroactively.',
  'bitcoin': 'The first and most well-known cryptocurrency, created in 2009 by the pseudonymous Satoshi Nakamoto.',
  'ethereum': 'A decentralized platform that runs smart contracts — programs that execute exactly as programmed without downtime or interference.',
  'smart contract': 'Self-executing code stored on a blockchain that automatically enforces the terms of an agreement when conditions are met.',
  'consensus mechanism': 'The method by which a blockchain network agrees on the current state of the ledger (e.g., Proof of Work, Proof of Stake).',
  'proof of work': 'A consensus mechanism where miners compete to solve complex math puzzles to validate transactions and create new blocks. Used by Bitcoin.',
  'proof of stake': 'A consensus mechanism where validators are chosen to create blocks based on how many coins they "stake" (lock up) as collateral.',
  'mining': 'The process of using computational power to validate transactions and add new blocks to a blockchain, earning cryptocurrency rewards.',
  'wallet': 'Software or hardware that stores your private keys and lets you send/receive cryptocurrency. Think of it like a digital keychain.',
  'private key': 'A secret code (like a password) that proves ownership of your cryptocurrency and lets you authorize transactions. Never share it!',
  'public key': 'A code derived from your private key that others can use to send you cryptocurrency. Like a bank account number.',
  'hash': 'A fixed-length string of characters generated from input data. Even a tiny change in input creates a completely different hash.',
  'block': 'A container of transaction data that is linked to previous blocks, forming the blockchain.',
  'node': 'A computer that participates in the blockchain network by storing a copy of the ledger and validating transactions.',
  'decentralization': 'Distributing control across many participants rather than relying on a single central authority (like a bank or government).',
  'defi': 'Decentralized Finance — financial services (lending, borrowing, trading) built on blockchain without traditional intermediaries like banks.',
  'nft': 'Non-Fungible Token — a unique digital certificate of ownership for items like art, music, or collectibles, stored on a blockchain.',
  'dao': 'Decentralized Autonomous Organization — a group governed by smart contracts and token-holder votes instead of traditional management.',
  'gas': 'A fee paid to process transactions on the Ethereum network. Higher complexity = more gas needed.',
  'token': 'A digital asset created on an existing blockchain (like Ethereum). Different from a "coin" which has its own blockchain.',
  'staking': 'Locking up your cryptocurrency to help validate transactions on a Proof of Stake network, earning rewards in return.',
  'yield farming': 'Lending or staking crypto across DeFi protocols to maximize returns — like shopping for the best savings account rates.',
  'liquidity pool': 'A pool of tokens locked in a smart contract that enables decentralized trading, lending, and other DeFi functions.',
  'impermanent loss': 'A temporary loss that liquidity providers experience when the price ratio of pooled tokens changes compared to simply holding them.',
  'dapp': 'Decentralized Application — an app that runs on a blockchain network instead of centralized servers.',
  'web3': 'The vision of a decentralized internet where users own their data and digital assets, powered by blockchain technology.',
  'layer 2': 'A secondary protocol built on top of a blockchain (Layer 1) to improve speed and reduce costs (e.g., Lightning Network, Rollups).',
  'rollup': 'A Layer 2 scaling solution that bundles many transactions together off-chain and posts a summary to the main chain.',
  'merkle tree': 'A data structure that efficiently summarizes and verifies large sets of data. Used in blockchains to verify transaction integrity.',
  'fork': 'A change to a blockchain\'s rules. A "hard fork" creates a new chain; a "soft fork" is backward-compatible.',
  'altcoin': 'Any cryptocurrency other than Bitcoin. Examples: Ethereum, Solana, Cardano.',
  'stablecoin': 'A cryptocurrency designed to maintain a stable value, usually pegged to a fiat currency like the US dollar (e.g., USDC, USDT).',
  'market cap': 'The total value of a cryptocurrency, calculated as price × circulating supply. Used to rank cryptocurrencies by size.',
  'whale': 'An individual or entity that holds a very large amount of a cryptocurrency, able to influence the market with their trades.',
  'rug pull': 'A scam where developers abandon a project and run away with investors\' funds. Common in DeFi and NFT spaces.',
  'seed phrase': 'A series of 12-24 words that can restore your cryptocurrency wallet. Guard it like the master password to your digital vault.',
  'airdrop': 'Free distribution of tokens to wallet addresses, often used to promote new projects or reward early users.',
  'bridge': 'A protocol that allows transferring assets between different blockchains (e.g., moving tokens from Ethereum to Polygon).',
  'oracle': 'A service that feeds real-world data (prices, weather, sports scores) into smart contracts on the blockchain.',
  'txid': 'Transaction ID — a unique identifier for a specific transaction on the blockchain, used to track and verify it.',
};

export default glossary;
